# Generated by Django 3.0.4 on 2020-04-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0002_auto_20200409_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='image',
            new_name='education_image',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='name',
            new_name='education_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='project_image',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='summary',
            new_name='project_summary',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='title',
            new_name='project_title',
        ),
    ]
