# Generated by Django 3.0.4 on 2020-04-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0003_auto_20200410_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_image',
        ),
    ]
