# Generated by Django 3.0.4 on 2020-04-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Message',
        ),
    ]
